-- MEDIANA
CREATE OR REPLACE FUNCTION _FINAL_MEDIAN(NUMERIC[])
    RETURNS NUMERIC AS
$$
    SELECT AVG(VAL)
    FROM (
        SELECT VAL
        FROM UNNEST($1) VAL
        ORDER BY 1
        LIMIT 2
        OFFSET CASE
                   WHEN ARRAY_UPPER($1, 1) % 2 = 1 THEN
                       CEIL(ARRAY_UPPER($1, 1) / 2.0) - 1
                   ELSE
                       ARRAY_UPPER($1, 1) / 2
               END
    ) SUB;
$$
LANGUAGE 'SQL' IMMUTABLE;

CREATE AGGREGATE median(NUMERIC) (
    SFUNC = array_append,
    STYPE = NUMERIC[],
    FINALFUNC = _FINAL_MEDIAN,
    INITCOND = '{}'
);


SELECT MEDIAN(QTD) AS "MEDIANA"
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01';

SELECT MEDIAN(QTD) AS "MEDIANA"
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02';

SELECT MEDIAN(QTD) AS "MEDIANA"
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03';


INSERT INTO MAQUINAS VALUES('MAQUINA 01', 11,15.9);
INSERT INTO MAQUINAS VALUES('MAQUINA 02', 11,15.4);
INSERT INTO MAQUINAS VALUES('MAQUINA 03', 11,15.7);
INSERT INTO MAQUINAS VALUES('MAQUINA 01', 12,30);
INSERT INTO MAQUINAS VALUES('MAQUINA 02', 12,24);
INSERT INTO MAQUINAS VALUES('MAQUINA 03', 12,45);
