/* MEDIDAS ESTATÍSTICAS */

-- MOSTRANDO UMA QUANTIDADE LIMITADA DE LINHAS;
SELECT * FROM FUNCIONARIOS
LIMIT 10;


-- QUAL O GASTO TOTAL DE SALARIO PAGO PELA EMPRESA;
SELECT SUM(SALARIO) AS "GASTO TOTAL DE SALARIO" FROM FUNCIONARIOS;

	-- QUAL O GASTO TOTAL DE SALARIO DE CADA DEPARTAMENTO
	SELECT DEPARTAMENTO, SUM(SALARIO) AS "GASTO TOTAL DE SALARIO" FROM FUNCIONARIOS
	GROUP BY DEPARTAMENTO;

		-- QUAL O TOTAL E A MEDIA DE SALARIO PAGA AO FUNCIONARIOS, POR DEPARTAMENTO;
		SELECT DEPARTAMENTO, SUM(SALARIO) AS "GASTO TOTAL DE SALARIO", AVG(SALARIO) AS "MEDIA DE SALARIO POR DEPARTAMENTO"
		FROM FUNCIONARIOS
		GROUP BY DEPARTAMENTO;

			-- ORDENANDO O RESULTADO POR COLUNA DESEJADA. SEMPRE APONTAR O NÚMERO DA COLUNA;
			SELECT DEPARTAMENTO, SUM(SALARIO) AS "GASTO TOTAL DE SALARIO", AVG(SALARIO) AS "MEDIA DE SALARIO POR DEPARTAMENTO"
			FROM FUNCIONARIOS
			GROUP BY DEPARTAMENTO
			ORDER BY 3;

				-- ORDENANDO DE FORMA ASCENDENTE;
				SELECT DEPARTAMENTO, SUM(SALARIO) AS "GASTO TOTAL DE SALARIO", AVG(SALARIO) AS "MEDIA DE SALARIO POR DEPARTAMENTO"
				FROM FUNCIONARIOS
				GROUP BY DEPARTAMENTO
				ORDER BY 3 ASC;

				-- ORDENANDO DE FORMA ASCENDENTE;
				SELECT DEPARTAMENTO, SUM(SALARIO) AS "GASTO TOTAL DE SALARIO", AVG(SALARIO) AS "MEDIA DE SALARIO POR DEPARTAMENTO"
				FROM FUNCIONARIOS
				GROUP BY DEPARTAMENTO
				ORDER BY 3 DESC;