/* 	MONTANDO UMA UNICA QUERY CONTENDO TODAS AS MEDIDAS ESTATÍSTICAS:
	
	- QUANTIDADE
	- TOTAL
	- MEDIA
	- MAXIMO
	- MINIMO
	- AMPLITUDE
	- VARIANCIA
	- DESVIO PADRÃO
	- MEDIANA
	- MODA
	- COEFICIENTE DE VARIAÇÃO

*/


-- ELABORANDO A QUERY
SELECT	MAQUINA,
		COUNT(QTD) AS "QUANTIDADE",
		SUM(QTD) AS "TOTAL",
		ROUND(AVG(QTD),2) AS "MEDIA",
		MAX(QTD) AS "MAXIMO",
		MIN(QTD) AS "MINIMO",
		MAX(QTD) - MIN(QTD) AS "AMPLI. TOTAL",
		ROUND(VAR_POP(QTD),2) AS "VARIANCIA",
		ROUND(STDDEV_POP(QTD),2) AS "DESVIO PADRAO",
		ROUND(MEDIAN(QTD),2) AS "MEDIANA",
		ROUND((STDDEV_POP(QTD) / AVG(QTD)) * 100) AS "COEF. VARIACAO"
		FROM MAQUINAS
		GROUP BY MAQUINA
		ORDER BY 1;

