/* FUNÇÕES DE AGREGAÇÃO: FUNÇÕES QUE AGREGAM VALORES AVULSOS.
	- OS DADOS GERADOS POR ESSAS FUNÇÕES SÃO UTILIZADOS POR BUSINESS INTELIGENCE E DATA SCIENCE. */

-- TRAZER TODOS OS DADOS DA TABELA APONTADA;
SELECT * FROM FUNCIONARIOS;
SELECT * FROM DEPARTAMENTO;
SELECT * FROM LOCALIZACAO;


-- CONTAR TODAS AS OCORRÊNCIAS DE REGISTROS DENTRO DA TABELA APONTADA;
SELECT COUNT(*) FROM FUNCIONARIOS;
SELECT COUNT(*) FROM DEPARTAMENTO;
SELECT COUNT(*) FROM LOCALIZACAO;


-- AGRUPAR OS DADOS POR UM DETERMINADO PARÂMETRO. NESTE EXEMPLO, O PARÂMETRO É 'SEXO';
SELECT COUNT(*) FROM FUNCIONARIOS
GROUP BY SEXO;


	-- EXIBIR O NOME DA COLUNA DO PARÂMETRO DA CONTAGEM;
	SELECT SEXO, COUNT(*) AS 'QUANTIDADE' FROM FUNCIONARIOS
	GROUP BY SEXO;


-- MOSTRANDO O NÚMERO DE FUNCIONÁRIOS EM CADA DEPARTAMENTO;
SELECT DEPARTAMENTO, COUNT(*) FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;


-- EXIBINDO O MAIOR SALARIO DA TABELA;
SELECT MAX(SALARIO) AS "MAIOR SALARIO" FROM FUNCIONARIOS;

-- EXIBINDO O MENOR SALARIO DA TABELA;
SELECT MIN(SALARIO) AS "MENOR SALARIO" FROM FUNCIONARIOS;

	-- EXIBINDO O MAIOR E O MENOR SALARIO SIMULTANEAMENTE;
	SELECT MIN(SALARIO) AS "MENOR SALARIO", MAX(SALARIO) AS "MAIOR SALARIO"
	FROM FUNCIONARIOS; 

		-- EXIBINDO O MAIOR E O MENOR SALARIO POR DEPARTAMENTO;
		SELECT DEPARTAMENTO, MIN(SALARIO) AS "MENOR SALARIO", MAX(SALARIO) AS "MAIOR SALARIO"
		FROM FUNCIONARIOS
		GROUP BY DEPARTAMENTOS;

		-- EXIBINDO O MAIOR E O MENOR SALARIO POR SEXO;
		SELECT SEXO, MIN(SALARIO) AS "MENOR SALARIO", MAX(SALARIO) AS "MAIOR SALARIO"
		FROM FUNCIONARIOS
		GROUP BY SEXO;