-- MODA DO DATASET INTEIRO
SELECT QTD AS "QUANTIDADE", COUNT(*) AS "MODA"
FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC;
	-- HISTOGRAMA: GRÁFICO QUE FAZ A CONTAGEM DE ALGARISMOS.


-- QUAL O MÁXIMO, O MÍNIMO E AMPLITUDE DE CADA MÁQUINA?
SELECT 	MAQUINA,
		MAX(QTD) AS "MAXIMO",
		MIN(QTD) AS "MINIMO",
		MAX(QTD) - MIN(QTD) AS "AMPLITUDE"
		FROM MAQUINAS
		GROUP BY MAQUINA
		ORDER BY 4 DESC;

	-- INCLUINDO A MEDIA JUNTO AO MÁXIMO, MÍNIMO E AMPLITUDE DE CADA MÁQUINA
	SELECT 	MAQUINA,
			ROUND(AVG(QTD),2) AS "MEDIA",
			MAX(QTD) AS "MAXIMO",
			MIN(QTD) AS "MINIMO",
			MAX(QTD) - MIN(QTD) AS "AMPLITUDE"
			FROM MAQUINAS
			GROUP BY MAQUINA
			ORDER BY 4 DESC;
