-- CRIANDO A TABELA MAQUINAS(
CREATE TABLE MAQUINAS(
	MAQUINA VARCHAR(20),
	DIA INT,
	QTD NUMERIC(10,2)
);

-- IMPORTANDO ARQUIVO .CSV
COPY MAQUINAS
FROM 'C:\LogMaquinas.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM MAQUINAS;

/* MÉDIA */
-- QUAL A MÉDIA DE CADA MÁQUINA?
SELECT MAQUINA, AVG(QTD) AS "QUANTIDADE_MEDIA" FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 2 DESC;

	-- ARREDONDANDO VALORES
	SELECT MAQUINA, ROUND(AVG(QTD),2) AS "QUANTIDADE_MEDIA" FROM MAQUINAS
	GROUP BY MAQUINA
	ORDER BY 2 DESC;


/* MODA */
-- QUAL A MODA DAS QUANTIDADES DE MÁQUINA?
SELECT MAQUINA, QTD, COUNT(*) AS "MODA" FROM MAQUINAS
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC;

	-- QUAL A MODA DAS QUANTIDADES DE CADA MAQUINAESTATISTICA?
	SELECT MAQUINA, QTD COUNT(*) AS "QUANTIDADE" FROM MAQUINAS
	WHERE MAQUINA = 'Maquina 01'
	GROUP BY MAQUINA, QTD
	ORDER BY 3 DESC
	LIMIT 1;

	-- QUAL A MODA DAS QUANTIDADES DE CADA MAQUINA?
	SELECT MAQUINA, QTD COUNT(*) AS "QUANTIDADE" FROM MAQUINAS
	WHERE MAQUINA = 'Maquina 02'
	GROUP BY MAQUINA, QTD
	ORDER BY 3 DESC
	LIMIT 1;

	-- QUAL A MODA DAS QUANTIDADES DE CADA MAQUINA?
	SELECT MAQUINA, QTD COUNT(*) AS "QUANTIDADE" FROM MAQUINAS
	WHERE MAQUINA = 'Maquina 03'
	GROUP BY MAQUINA, QTD
	ORDER BY 3 DESC
	LIMIT 1;